#!/bin/bash
# Seed Allo with 150+ memories for HNSW testing

echo "=== Seeding Allo with test data ==="

# Personal
allo remember "My name is Jason, I'm 46, and I live in Lynchburg, Virginia"
allo remember "I grew up loving computers and started coding as a teenager"
allo remember "I prefer working late at night when it's quiet"
allo remember "My favorite programming language is TypeScript"
allo remember "I drink coffee every morning, usually black"
allo remember "I value clean code and good documentation"
allo remember "I'm a dog person, always have been"
allo remember "My birthday is in the spring"
allo remember "I enjoy reading about AI and machine learning"
allo remember "I prefer dark mode in all my editors and apps"

# Terronex & Business
allo remember "I'm the CEO of Terronex, a tech company I founded"
allo remember "Terronex builds AI-native tools and formats"
allo remember "The company domain is terronex.dev, hosted on Cloudflare Pages"
allo remember "Our GitHub organization is terronexdev with 8 public repos"
allo remember "Business model is open core — free SDKs, paid Studio Pro"
allo remember "We use MIT license for all open source projects"
allo remember "LLC formation costs about 100 dollars and is still pending"
allo remember "Stripe payment setup is a blocker for launching paid products"
allo remember "Revenue goal is to monetize AIF-BIN Studio Pro subscriptions"
allo remember "Target market is AI developers, researchers, and enterprises"

# AIF-BIN
allo remember "AIF-BIN is a binary format for semantic search in a single file"
allo remember "AIF-BIN works offline, no server needed, privacy-first"
allo remember "Provisional patent for AIF-BIN was filed February 1, 2026"
allo remember "Utility patent deadline is February 1, 2027"
allo remember "AIF-BIN v3 includes HNSW indexing, temporal decay, and summarization"
allo remember "We built 8 SDKs for AIF-BIN: Python, JavaScript, Rust, Go, C#, Java, Swift, Kotlin"
allo remember "48 integrations built for AIF-BIN covering frameworks, editors, browsers, chatbots"
allo remember "AIF-BIN Studio is the desktop app for managing memory files"
allo remember "AIF-BIN uses MessagePack for binary serialization"
allo remember "The format supports encryption with AES-256-GCM and Argon2id KDF"

# Engram
allo remember "Engram is the neural memory tree format, published as @terronex/engram on npm"
allo remember "Engram v1.0.4 achieved 400x performance improvement"
allo remember "Engram uses HNSW indexing for fast approximate nearest neighbor search"
allo remember "The Engram format supports text, image, audio, and code content types"
allo remember "Engram files use the .engram extension"
allo remember "Engram nodes have temporal tiers: hot, warm, cold, archive"
allo remember "Engram supports parent-child hierarchical memory trees"
allo remember "Engram was published to npm on February 22, 2026"
allo remember "The Engram spec includes entities, links, and deltas"
allo remember "Engram embedding dimensions are configurable, default 384"

# Rex
allo remember "Rex is a multi-agent AI orchestration system I'm building"
allo remember "Rex uses pure AIF-BIN v3 for memory with BrainV3 architecture"
allo remember "Rex repo is at Terronex-dev/rex on GitHub, private"
allo remember "Rex memory was overhauled February 16 with 93.3% recall accuracy"
allo remember "Rex has 135 tests passing and 120+ commits"
allo remember "Rex BrainV3 uses single-file memory with temporal tiers"
allo remember "Rex includes HNSW indexing and intelligent compaction"
allo remember "Rex is standalone, not a fork or plugin of OpenClaw"
allo remember "Rex handles multi-agent coordination and task delegation"
allo remember "Rex memory uses cross-model embedding which required re-embedding with matching models"

# Allo
allo remember "Allo is my neural memory assistant CLI built on Engram"
allo remember "Allo supports Anthropic, OpenAI, Ollama, and Google for LLM"
allo remember "Allo has an interactive menu, chat mode, and onboarding wizard"
allo remember "Allo uses Xenova/all-MiniLM-L6-v2 for local embeddings"
allo remember "Allo config is stored at ~/.allo/config.json"
allo remember "Allo supports OAuth authentication with Anthropic"
allo remember "Allo chat mode uses memories as context for LLM conversations"
allo remember "Allo color scheme: amber primary, green success, purple accent, coral error"
allo remember "Allo was built on February 22, 2026 with 22 passing tests"
allo remember "Allo remember-file command can ingest documents into memory"

# Tech Stack
allo remember "My tech stack is TypeScript, Node.js, and Rust"
allo remember "I host websites on Cloudflare Pages"
allo remember "I use GitHub for version control and CI/CD"
allo remember "Vercel CLI is available for deployment at v50.5.0"
allo remember "I use Ollama for running local AI models"
allo remember "Models I run locally: gemma3:12b, llama3.1:8b, phi3:mini, qwen2.5-coder:7b"
allo remember "I use nomic-embed-text for local embeddings via Ollama"
allo remember "ElevenLabs is configured for text-to-speech with Chris voice"
allo remember "HuggingFace token is configured for model access"
allo remember "Google Workspace integration handles email, calendar, drive, and tasks"

# Development Lessons
allo remember "Smaller commits beat big features — ship atomically"
allo remember "Asset reuse is multiplicative — built 6 games reusing kawaii animals"
allo remember "Patent before launch — provisional patent gives 12-month runway"
allo remember "Documentation compounds and reduces sales friction"
allo remember "Verify baselines before optimization — avoid false improvements"
allo remember "Bigger chunks equal better recall — 512-word chunks scored 82.9% vs 600-char at 57.6%"
allo remember "Pure cosine beats hybrid BM25 plus cosine for semantic memory"
allo remember "Cross-model embedding search is useless — must re-embed with matching model"
allo remember "Sub-agent cron loops need explicit stop conditions to avoid wasted tokens"
allo remember "Manual integration beats process restart for complex system changes"

# AI & Models
allo remember "Claude Opus 4.6 is my primary AI model for complex tasks"
allo remember "Gemini Flash is unreliable for complex cron jobs — crashed mid-run"
allo remember "Sub-agents can ghost on vague instructions — always be explicit"
allo remember "MiniLM produces 384-dimensional embeddings"
allo remember "Nomic-embed-text produces 768-dimensional embeddings"
allo remember "BGE-small is good for short text, BGE-large for best accuracy"
allo remember "mxbai-embed-large produces 1024-dimensional embeddings"
allo remember "Anthropic OAuth tokens start with sk-ant-oat prefix"
allo remember "OpenAI text-embedding-3-small is paid but highest quality embeddings"
allo remember "Ollama runs on localhost port 11434"

# Infrastructure
allo remember "Running on WSL2 with Ubuntu on Windows"
allo remember "SSH keys configured for GitHub authentication"
allo remember "Cloudflare API token is configured for Pages deployment"
allo remember "Node.js v22.22.0 is installed"
allo remember "OpenClaw is my AI assistant framework running the gateway"
allo remember "Gateway runs as a daemon service on the machine"
allo remember "Security reports run automatically and email results"
allo remember "CEO reports are generated and emailed three times daily"
allo remember "Legal compliance reports are generated weekly"
allo remember "Memory files are synced to AIF-BIN format automatically"

# Projects & Ideas
allo remember "ROW Manager was removed from Vercel, planning to go another route later"
allo remember "AIF-BIN Studio Pro will be the paid tier with advanced features"
allo remember "Planning to build a tree browser UI for Allo"
allo remember "Want to add import from Markdown and Obsidian to Allo"
allo remember "Watch mode for Allo would auto-ingest new files"
allo remember "Built 6 games overnight reusing kawaii animal assets"
allo remember "TerraTitle is a legal document analysis tool using HuggingFace"
allo remember "VIbewear uses code-specific AI models for better Kotlin generation"
allo remember "LFO is a content-based file organization project"
allo remember "Web Inspector for AIF-BIN is compatible with v2 binary format"

# Dates & Milestones
allo remember "February 1, 2026: provisional patent filed, domain registered"
allo remember "February 10, 2026: AIF-BIN v3 completed with HNSW, temporal decay, summarization"
allo remember "February 16, 2026: Rex memory overhauled to pure AIF-BIN v3"
allo remember "February 22, 2026: Engram v1.0.4 published to npm"
allo remember "February 22, 2026: Allo v1.0.0 built and tested"
allo remember "January 2, 2027: domain renewal reminder for terronex.dev"
allo remember "February 1, 2027: utility patent deadline"
allo remember "January 26, 2026: Google Workspace v5.0 integration completed"
allo remember "January 26, 2026: HuggingFace integration authenticated"
allo remember "January 27, 2026: Clawd avatar generated and set on Telegram"

# Preferences & Style
allo remember "No emoji in documentation — clean professional text only"
allo remember "Concise responses preferred — value density over verbosity"
allo remember "Organization matters — likes things tidy and well-structured"
allo remember "Systematic approaches valued over ad-hoc solutions"
allo remember "Dark mode preferred in all applications"
allo remember "MIT license preferred for all open source projects"
allo remember "Prefer local-first architecture over cloud dependencies"
allo remember "Progressive testing ensures real transformation"
allo remember "Frameworks produce genuine behavioral change when applied progressively"
allo remember "Quality validation essential to confirm genuine capability"

# Security
allo remember "All ports are bound to localhost for security"
allo remember "No unauthorized SSH keys should exist on the system"
allo remember "Ollama is restricted to 127.0.0.1 only"
allo remember "OpenClaw directory has proper file permissions"
allo remember "Security audits run automatically and report via email"
allo remember "AIF-BIN supports AES-256-GCM encryption for memory files"
allo remember "Argon2id is used for key derivation in encrypted files"
allo remember "Private data should never be exfiltrated"
allo remember "Use trash instead of rm for recoverable deletes"
allo remember "Ask before running destructive commands"

# Misc Knowledge
allo remember "Cosine similarity measures angle between vectors, range -1 to 1"
allo remember "HNSW stands for Hierarchical Navigable Small World graph"
allo remember "Embeddings convert text to numerical vectors representing meaning"
allo remember "Semantic search finds results by meaning, not keywords"
allo remember "MessagePack is faster and smaller than JSON for binary data"
allo remember "Float32Array gets corrupted by msgpackr — convert to number array first"
allo remember "HNSW graph connectivity is poor with fewer than 100 nodes"
allo remember "Temporal decay reduces relevance of old memories over time"
allo remember "Hot memories are recently accessed, archive memories are old and unused"
allo remember "Brute force cosine search is more reliable than HNSW for small datasets"

echo ""
echo "=== Done! ==="
allo stats
